INSERT INTO `npc_text` VALUES ('7046', 'Look for it high up on the west side of the Valley of Strength. They\'ll only let you in if you\'re an officer! Talk to Sergeant Ba\'sha outside otherwise.', 'Look for it high up on the west side of the Valley of Strength. They\'ll only let you in if you\'re an officer! Talk to Sergeant Ba\'sha outside otherwise.', '1', '80', '0', '0', '0', '0', '0', '0', 'You want the Hall of Legends. It\'s high above the Valley of Strength on the west side. If you\'re not an officer you can\'t get in, but you can still talk to Sergeant Ba\'sha outside.', 'You want the Hall of Legends. It\'s high above the Valley of Strength on the west side. If you\'re not an officer you can\'t get in, but you can still talk to Sergeant Ba\'sha outside.', '1', '20', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `npc_text` VALUES ('7047', 'All of a sudden you\'re a \'Defender of the Alliance\' are you?! Well, I suppose you\'ll be wanting to head to the Champions\' Hall now. It\'s over in Old Town, but they won\'t let you in unless you\'re an officer, so you might just have to settle for talking to Officer Areyn outside. Move along now.', 'All of a sudden you\'re a \'Defender of the Alliance\' are you?! Well, I suppose you\'ll be wanting to head to the Champions\' Hall now. It\'s over in Old Town, but they won\'t let you in unless you\'re an officer, so you might just have to settle for talking to Officer Areyn outside. Move along now.', '7', '80', '0', '0', '0', '0', '0', '0', 'Well, well, moving up in the world are we? You\'re looking for the Champions\' Hall, and you\'ll find it on the southeast end of Old Town. If you\'re an officer you can enter the hall, otherwise you can still speak to Officer Areyn standing outside. Good luck!', 'Well, well, moving up in the world are we? You\'re looking for the Champions\' Hall, and you\'ll find it on the southeast end of Old Town. If you\'re an officer you can enter the hall, otherwise you can still speak to Officer Areyn standing outside. Good luck!', '7', '20', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0');


UPDATE `creature_template` SET `spell1`=8378, `AIName`='TotemAI', `ScriptName`='' WHERE `entry`=6066;



INSERT INTO `creature_template_addon` (`entry`, `patch`, `mount`, `bytes1`, `b2_0_sheath`, `b2_1_flags`, `emote`, `moveflags`, `auras`) VALUES (6066, 0, 0, 0, 0, 0, 0, 0, '8378');
