(123, 'Go to Marshal Dughan in Goldshire and give him The Collector\'s Schedule.');
(212, 'Kill a Cold Eye Basilisk, get a Chilled Basilisk Haunch, and return it to Angus Stern in the Blue Recluse.');
(216, 'Take down 8 Thistlefur Avengers and 8 Thistlefur Shaman; most are located east of Zoram Strand in Thistlefur Village.  Once completed, return to Karang Amakkar at Zoram\'gar Outpost, Ashenvale.');
(275, 'Kill 8 Fen Creepers, then return to Rethiel the Greenwarden in the Wetlands.');
(303, 'Motley Garmason at Dun Modr wants you to kill 10 Dark Iron Dwarves,  5 Dark Iron Tunnelers, 5 Dark Iron Saboteurs and 5 Dark Iron Demolitionists.');
(341, 'Bring pages 18, 20, 21 and 24 of Nesingwary\'s The Green Hills of Stranglethorn to Barnil Stonepot in order to complete Chapter III.');
(349, 'Speak with Witch Doctor Unbagwa.');
(475, 'Seek out Gaerolas Talvethren in Starbreeze Village.\r\n');
(518, 'Kill 10 Crushridge Maulers for Melisara in Tarren Mill.');
(532, 'Kill Magistrate Burnside and 4 Hillsbrad Councilmen.  Destroy the Hillsbrad Proclamation.  Steal the Hillsbrad Town Registry.  Report back to Darthalia in Tarren Mill afterwards.');
(541, 'Travel to Dun Garok and kill 8 Mountaineers, 4 Riflemen, 2 Priests and Captain Ironhill and report back to Darthalia in Tarren Mill.');
(607, 'Bring Shaky\'s Payment to "Sea Wolf" MacKinley.');
(640, 'Retrieve the 5 Sigil Fragments from the defenders in Stromgarde, and bring them to Tor\'gan in Hammerfall.');
(682, 'Bring 7 Stromgarde Badges to Captain Nials at Refuge Pointe.');
(1022, 'Go to the Howling Vale and study the Tome of Mel\'Thandris, then return to Sentinel Melyria Frostshadow at Forest Song.');
(1031, 'Kill Geltharis and return the Branch of Cenarius to Illiyana at Forest Song.');
(1032, 'Bring 16 Satyr Horns to Illiyana in Forest Song.');
(1073, 'Bring 4 Minor Mana Potions and 2 Elixirs of Minor Fortitude to Lomac Gearstrip in Ironforge.');
(1132, 'Speak with Fiora Longears in the tavern at Theramore Isle in Dustwallow Marsh.');
(1156, 'TODO');
(1168, 'Tharg in Brackenwall Village wants you to kill 10 Firemane Scouts, 10 Firemane Ash Tails, and 5 Firemane Scalebanes.');
(1169, 'Draz\'Zilb in Brackenwall Village would like you to bring him 7 Searing Tongues and 7 Searing Hearts.');
(1177, 'Mudcrush Durtfeet in northern Dustwallow wants 8 Mirefin Heads.');
(1206, 'Bring 20 Unpopped Darkmist Eyes to "Swamp Eye" Jarl at the Swamplight Manor.');
(1219, 'Bring the Spy\'s Report to Lieutenant Aden in Theramore.');
(1267, '');
(1282, 'Speak with Captain Garran Vimes on the top floor of Foothold Citadel.');
(1302, 'Speak with Clerk Lendry at Foothold Citadel in Theramore.');
(1322, 'Acquire 5 Acidic Venom Sacs for Do\'gol in Brackenwall Village.');
(1489, 'Speak with Hamuul Runetotem.');
(1578, 'Bring 6 Copper Axes and 6 Copper Chain Belts to Thorvald in the southern guard tower of Loch Modan.');
(1582, 'Bring 1 Embossed Leather Gloves, 5 Embossed Leather Boots and 5 Embossed Leather Cloaks to Lotherias in Darnassus.');
(1691, 'Take down 10 Wastewander Shadow Mages, 8 Wastewander Rogues, and 6 Wastewander Assassins for Chief Engineer Bilgewhizzle in Gadgetzan.\r\n');
(1842, 'Bring 7 Uncloven Satyr Hooves to Ula\'elek at Sen\'jin Village in Durotar.');
(1899, 'Bring Andron\'s Ledger to Mennet Carkad in the Rogues\' Quarter of Undercity.');
(1921, 'Bring 10 Linen Cloth and the 6 Charged Rift Gems to Wynne Larson in Stormwind.');
(1961, 'Bring 10 Linen Cloth and 6 Dalaran Mana Gems to Josef Gregorian.');
(2200, 'Search for clues as to the current disposition of Talvash\'s necklace within Uldaman.  The slain paladin he mentioned was the person who had it last.');
(2206, 'Find the Defias Dockmaster and recover the Shipping Schedule for Master Mathias Shaw.\r\n');
(2242, 'Find Sethir the Ancient and bring back any clues that you may discover to Syurna.\r\n');
(2259, 'Contact Erion Shadewhisper in Darnassus.\r\n');
(2260, 'Travel to Stormwind City and seek council with Renzik "The Shiv."\r\n');
(2281, 'Venture forth to Lakeshire in the Redridge Mountains and speak with Lucius.\r\n');
(2300, 'Travel to Stormwind and seek out Renzik "The Shiv."\r\n');
(2359, 'Steal the Defias Tower Key, break into the Defias Tower and uncover the contents of the Duskwood Chest. Take whatever information you find back to Mathias Shaw in Stormwind. Read Kearnen\'s Journal to gain insight about the tower.\r\n');
(2378, 'Journey to Orgrimmar and speak with Shenthul at the Cleft of Shadow.$B$B$B$B');
(2381, 'Bring the Southsea Treasure back to Wrenix the Wretched in Ratchet. Do not forget to get an E.C.A.C. and Thieves\' Tools from Wrenix\'s Gizmotronic Apparatus. You will need both of these items to complete your mission.$B$BShould you be attacked by any unusually hostile parrots, use your E.C.A.C.!\r\n\r\n');
(2478, 'Steal Silixiz\'s Tower Key from Foreman Silixiz, then kill two Mutated Venture Co. Drones, two Venture Co. Patrollers, and two Venture Co. Lookouts.$B$BAssassinate Grand Foreman Gallywix and take his head, then pick the lock on Gallywix\'s lockbox and steal the Cache of Zanzil\'s Altered Mixture. Take the Cache and Gallywix\'s Head back to Shenthul in Orgrimmar for further instruction.\r\n');
(2479, 'Travel to Tarren Mill in Hillsbrad Foothills and deliver the Sample of Zanzil\'s Mixture to Serge Hinott.$B$BTo get to Tarren Mill, take the Zeppelin to the Undercity and follow the road south through Silverpine and towards Hillsbrad. Follow the signs!\r\n\r\n');
(2583, 'Bring three Blasted Boar Lungs, two Scorpok Pincers, and one Basilisk Brain to Bloodmage Drazial.\r\n');
(2584, 'Bring three Blasted Boar Lungs, two Scorpok Pincers, and one Basilisk Brain to Bloodmage Drazial.\r\n');
(2585, 'Bring three Scorpok Pincers, two Vulture Gizzards, and one Blasted Boar Lung to Bloodmage Drazial.\r\n');
(2601, 'Bring ten Basilisk Brains and two Vulture Gizzards to Bloodmage Lynnore.\r\n');
(2603, 'Bring ten Vulture Gizzards and two Snickerfang Jowls to Bloodmage Lynnore.\r\n');
(2604, 'Bring ten Vulture Gizzards and two Snickerfang Jowls to Bloodmage Lynnore.\r\n');
(2608, '/Lay down to be examined by Doc Mixilpixil. How can he find the cure if he can\'t find the cause?\r\n');
(2751, 'Bring two Patterned Bronze Bracers, two Bronze Greatswords, and two Sharp Claws to Orokk Omosh in Orgrimmar.\r\n');
(2756, 'Bring four Steel Breastplates and four Steel Plate Helms to Aturk the Anvil in Orgrimmar.\r\n');
(2760, 'Speak with Galvan the Ancient in Stranglethorn Vale.\r\n');
(2772, 'Bring two Heavy Mithril Boots and one Ornate Mithril Pants to Trenton Lighthammer.\r\n');
(2841, 'Retrieve the Rig Blueprints and Thermaplugg\'s Safe Combination from Gnomeregan and bring them to Nogg in Orgrimmar.\r\n');
(2962, 'Travel to Gnomeregan and bring back High Potency Radioactive Fallout. Be warned, the fallout is unstable and will collapse rather quickly.$B$BOzzie will also require your Heavy Leaden Collection Phial when the task is complete.\r\n');
(3084, 'Read the Rune-Inscribed Tablet and speak to Shikrik in the Valley of Trials.');
(3181, 'Take Margol\'s Gigantic Horn to Mountaineer Pebblebitty.\r\n');
(3367, 'Help Dorius get back to Ironforge.\r\n');
(3372, 'Find the Mysterious Artifact being guarded by the Twilight\'s Hammer Idolaters in the northwest quadrant of the Searing Gorge and bring it to the Altar of Suntara in the Slag Pit.\r\n');
(3378, 'Find the Prayer to Elune and take it to Astarii Starseeker in Darnassus.\r\n');
(3379, 'Kill the group of Shadow Silk Poachers that wander the Searing Gorge. Nilith has reason to believe that there are five of them that need to be exterminated. Return to Nilith in the Searing Gorge when this task is complete.\r\n');
(3385, 'Slay Trade Master Kovic and his minion Clunk. Retrieve the Trader\'s Satchel from his corpse and return it to Nilith.\r\n');
(3402, 'Speak with Vizzklick in Gadgetzan.\r\n');
(3453, 'Wait for Kalaran Windblade to complete the Torch of Retribution.\r\n');
(3463, 'Set the North, South, East, and West Sentry Towers on fire by using the Torch of Retribution inside each of the buildings. \r\n');
(3501, 'Bring Kum\'isha Imperfect Draenethyst Fragments and be rewarded for each one you turn in.\r\n');
(3502, 'Bring Kum\'isha Imperfect Draenethyst Fragments. Any form of monster in the Blasted Lands could be carrying a fragment.\r\n');
(3511, 'Take the temper back to Loramus Thalipedes.\r\n');
(3602, 'Recover twenty Crystallized Azsharite from southern Azshara. You may use the Felhound to assist you in \'sniffing\' out the location of cleverly hidden deposits.$B$BReturn to Loramus when the task is complete.\r\n');
(3627, 'Slay Grol the Destroyer, Lady Sevine, and Archmage Allistarj. From their corpses take the Amulet of Grol, the Amulet of Sevine, and the Amulet of Allistarj.$B$BRemember to USE your Enchanted Azsharite Fel Weaponry to weaken the triad. They cannot be killed otherwise - but use them wisely...\r\n');
(3628, 'Destroy Razelikh the Defiler and return the Severed Horn of the Defiler to the Fallen Hero of the Horde. You will also need to return the Ward of the Defiler so that the Fallen Hero can destroy it, preventing it from ever falling into the wrong hands.\r\n');
(3802, 'Slay Fineous Darkvire and recover the great hammer, Ironfel. Take Ironfel to the Shrine of Thaurissan and place it on the statue of Franclorn Forgewright.');
(3822, 'Recover Sha\'ni\'s Nose-Ring from Krom\'Grul and return it to Thal\'trak in Kargath. Search the various caves and mines in Dreadmaul Rock.\r\n');
(3824, 'Find Gor\'tesh, somewhere to the west of Dreadmaul Rock. Kill Gor\'tesh and then take Gor\'tesh\'s Lopped Off Head back to Oralius in Burning Steppes.\r\n');
(3906, 'Travel to the quarry in Blackrock Mountain and slay Overmaster Pyron. Return to Thunderheart when you have completed this assignment.');
(3907, 'Enter Blackrock Depths and track down Lord Incendius. Slay him and return any source of information you may find to Thunderheart.\r\n');
(4001, 'Speak with Kharan Mighthammer and gather information about Princess Moira Bronzebeard\'s kidnapping. Take that information to Thrall in Orgrimmar.$B$BYou recall Gor\'shak mentioning that Kharan is being held in a cell nearby.\r\n');
(4003, 'Slay Emperor Dagran Thaurissan and free Princess Moira Bronzebeard from his evil spell. \r\n');
(4004, 'Return to Thrall!\r\n');
(4022, 'Show Cyrus Therepentous the Black Dragonflight Molt you received from Kalaran Windblade.\r\n');
(4024, 'Travel to Blackrock Depths and slay Bael\'Gar.$B$BYou only know that the giant resides inside Blackrock Depths. Remember to use the Altered Black Dragonflight Molt on Bael\'Gar\'s remains to capture the Fiery Essence.$B$BReturn the Encased Fiery Essence to Cyrus Therepentous.$B$B');
(4062, 'Take the Elemental Shard Sample to Lotwil Veriatus.$B$BYou recall Theodora saying that Lotwil was stationed in a camp to the east.\r\n');
(4081, 'Venture to Blackrock Depths and destroy the vile aggressors!$B$BWarlord Goretooth wants you to kill 15 Anvilrage Guardsmen, 10 Anvilrage Wardens and 5 Anvilrage Footmen. Return to him once your task is complete.$B$B');
(4122, 'Travel to the Burning Steppes and find Grark Lorkrub. You recall Lexlort mentioning that he was last seen in a massive Blackrock fortress.$B$BWhen you find Grark Lorkrub, use the Thorium Shackles to bind him and then lead him back through Blackrock Mountain to the Searing Gorge. Lexlort will have his men waiting on the other side to take Grark into custody.\r\n');
(4186, 'Take Bolvar\'s Decree to Magistrate Solomon in Lakeshire.\r\n');
(4286, 'Travel to Blackrock Depths and recover 20 Dark Iron Fanny Packs. Return to Oralius when you have completed this task. You assume that the Dark Iron dwarves inside Blackrock Depths carry these \'fanny pack\' contraptions.\r\n');
(4362, 'Return to Blackrock Depths and rescue Princess Moira Bronzebeard from the evil clutches of Emperor Dagran Thaurissan.\r\n');
(4506, 'Take Winna\'s kitten to the corrupted moonwell, release it, then bring it back to Winna.$B$BOnce you have returned to Winna, click on the cat to release it to Winna.');
(4641, 'Speak with Gornek. You recall Kaltunk marking your map with his location and mentioning that Gornek resided in the Den, a building to the west. \r\n\r\n');
(4862, 'Travel to Blackrock Spire and collect 15 Spire Spider Eggs for Kibler.$B$BBy the sound of it, these eggs could be found near spiders.\r\n');
(4971, 'Use the Temporal Displacer near one of Andorhal\'s silos and uncover Temporal Parasites.$B$BSlay 10 Temporal Parasites, and then return the Temporal Displacer to Chromie in the Andorhal Inn, Western Plaguelands.');
(4982, 'Find Bijou\'s Belongings and return them to her. You recall her mentioning that she stashed them on the bottom floor of the city.\r\n');
(4983, 'Take Bijou\'s Reconnaissance Report back to Grandmaster Lexlort in Kargath.\r\n');
(4984, 'Destroy 8 Diseased Wolves, and then return to Mulgris Deepriver at the Writhing Haunt, Western Plaguelands.\r\n\r\n');
(5001, 'Find Bijou\'s Belongings and return them to her. Good luck!\r\n');
(5064, 'Locate and retrieve the three Secret Notes in Darkcloud Pinnacle.');
(5102, 'Travel to Blackrock Spire and destroy General Drakkisath. Return to Marshal Maxwell when the job is done.\r\n');
(5126, 'Speak with Lorax. Listen to what he has to say.\r\n');
(5164, 'Read from the Catalogue of the Wayward.\r\n');
(5212, 'Recover 10 Plagued Flesh Samples from Stratholme and return them to Betina Bigglezink. You suspect that any creature in Stratholme would have said flesh sample.');
(5213, 'Travel to Stratholme and search the ziggurats. Find and return new Scourge Data to Betina Bigglezink.\r\n');
(5214, 'Find Fras Siabi\'s smoke shop in Stratholme and recover a box of Siabi\'s Premium Tobacco. Return to Smokey LaRue when the job is done.\r\n');
(5263, 'Venture to Stratholme and destroy Baron Rivendare. Take his head and return to Duke Nicholas Zverenhoff.\r\n');
(5284, 'To become a Weaponsmith, you must make the following items and return them to Ironus: 4 Moonsteel Broadswords, 4 Massive Iron Axes, 2 Heavy Mithril Axes, and 2 Big Black Maces.\r\n');
(5302, 'To become a Weaponsmith, you must make the following items and return them to Borgosh: 4 Moonsteel Broadswords, 4 Massive Iron Axes, 2 Heavy Mithril Axes, and 2 Big Black Maces.\r\n');
(5305, 'Travel to Stratholme and kill the Crimson Hammersmith. Recover the Crimson Hammersmith\'s Apron and return to Lilith.\r\n');
(5381, 'Retrieve the Demon Box from Thunder Axe Fortress, and return it, along with the Demon Pick to Taiga Wisemane in Shadowprey Village.\r\n');
(5382, 'Find Doctor Theolen Krastinov inside the Scholomance. Destroy him, then burn the Remains of Eva Sarkhoff and the Remains of Lucien Sarkhoff. Return to Eva Sarkhoff when the task is complete.\r\n');
(5384, 'Return to the Scholomance with the Blood of Innocents. Find the porch and place the Blood of Innocents in the brazier. Kirtonos will come to feast upon your soul.$B$BFight valiantly, do not give an inch! Destroy Kirtonos and return to Eva Sarkhoff.\r\n');
(5482, 'Collect 10 Doom Weed and deliver them back to Junior Apothecary Holland.\r\n');
(5504, 'Bring 10 Argent Dawn Valor Tokens to Quartermaster Hasana at the Bulwark or Quartermaster Lightspark at Chillwind Camp, Western Plaguelands or Quartermaster Breechlock at Light\'s Hope Chapel, Eastern Plaguelands.');
(5544, 'Seek out the Carrion Grubs and Devourers of the region. Slay them and harvest their meat. Return to Tirion Fordring when you have gathered 15 Slabs of Carrion Worm Meat.\r\n');
(5581, 'Banish 6 Portals at Mannoroc Coven and return to Taiga Wisemane at Shadowprey Village.');
(5741, 'Get the Sceptre of Light and then return it to Azore Aldamort at the tower in Ethel Rethor.\r\n');
(5961, 'Speak with Nathanos Blightcaller in the Eastern Plaguelands. He is said to have taken up residence at the Marris Stead.\r\n');
(6027, 'Get the Book of the Ancients and return it to Azore Aldamort at the tower in Ethel Rethor.\r\n');
(6147, 'Return to Nathanos Blightcaller with the new information.\r\n');
(6184, 'Travel to Chillwind Camp in the Western Plaguelands and meet up with your contact, Flint Shadowmore.\r\n');
(6401, 'Tell Tammra Windfield in Sun Rock Retreat the good news.\r\n');
(6482, 'Escort Ruul, then speak with Yama Snowhoof in Splintertree Post.');
(6504, 'Find the 12 missing pages of the Shredder Operating Manual, and put them together to form Chapters 1, 2, and 3. Return the pages to Gurda Ragescar near Splintertree Post.\r\n');
(6523, 'Escort Kaya Flathoof to Camp Aparaje, and then return to Makaba Flathoof near the southeastern edge of Stonetalon.\r\n');
(6548, 'Kill 8 Grimtotem Ruffians and 6 Grimtotem Mercenaries, and then return to Makaba Flathoof near the southeastern edge of Stonetalon.\r\n');
(6567, 'Seek out Rexxar. The Warchief has instructed you as to his whereabouts. Search the paths of Desolace, between the Stonetalon Mountains and Feralas.');
(6570, 'Travel to the Wyrmbog in Dustwallow Marsh and seek out Emberstrife\'s Den. Once inside, wear the Amulet of Draconic Subversion and speak with Emberstrife.\r\n');
(6612, 'Travel to Gadgetzan in the Tanaris desert and speak with Dirge Quikcleave about advancing your cooking career.\r\n');
(6623, 'Travel to Hammerfall in the Arathi Highlands and speak with Doctor Gregory Victor about joining the ranks of Horde Trauma.\r\n');
(6629, 'Kill Grundig Darkcloud and 6 Grimtotem Brutes, and return to Makaba Flathoof near the southeastern edge of Stonetalon.\r\n');
(6805, 'Kill 15 Dust Stormers and 15 Desert Rumblers and then return to Duke Hydraxis in Azshara.');
(7028, 'Collect 15 Theradric Crystal Carvings for Willow in Desolace.');
(7201, 'Travel to Blackrock Depths and recover 10 Essence of the Elements. Your first inclination is to search the golems and golem makers. You remember Vivian Lagrave also muttering something about elementals.\r\n');
(7581, 'Travel to Dire Maul in Feralas and recover 15 Satyr Blood from the Wildspawn Satyr that inhabit the Warpwood Quarter. Return to Daio in the Tainted Scar when this is done.\r\n');
(7722, 'Somewhere in the Slag Pit of the Cauldron you will find the Secret Plans: Fiery Flux that Overseer Maltorius stole. Find those plans and return them to Master Smith Burninate in the Searing Gorge.\r\n');
(7736, 'Deliver 2 Incendosaur Scales, 4 Kingsblood and one Coal to Master Smith Burninate.');
(7828, 'Huntsman Markhor at Revantusk Village in the Hinterlands wants you to kill 10 Silvermane Stalkers and 10 Silvermane Howlers. Return to him once the task is complete.$B$BMarkhor mentioned that the wolves hide in the wilds of the Hinterlands.');
(7844, 'Mystic Yayo\'jin at Revantusk Village in the Hinterlands wants you to kill 15 Vilebranch Scalpers and 10 Vilebranch Soothsayers. Return to her when this task is complete.$B$BYayo\'jin indicated that these trolls could be found near the Shaol\'watha and Agol\'watha temples in the north by northeastern region of the Hinterlands.');
(7845, 'Primal Torntusk at Revantusk Village in the Hinterlands wants you to rescue her mate, Elder Torntusk, from Jintha\'alor.$B$BYou have been told that he is being held prisoner atop Jintha\'alor, the Vilebranch capital city located in the southern region of the Hinterlands.');
(7846, 'Elder Torntusk at Jintha\'alor wants you to kill Hitah\'ya the Keeper to get the Shackle Key to his bindings. Return to Elder Torntusk when you have recovered the key.');
(7861, 'You have been ordered to slay Vile Priestess Hexx and 10 Vilebranch Aman\'zasi Guards. See Primal Torntusk at Revantusk Village in the Hinterlands once this task is complete.$B$BVile Priestess Hexx and the Aman\'zasi Guards can be found atop Jintha\'alor in the Hinterlands.');
(8464, 'Salfa wants you to kill 8 Winterfall Totemics, 8 Winterfall Den Watchers, and 8 Winterfall Pathfinders.');
(8466, 'Some of the Deadwood furbolgs wear a distinctive headdress that may be used as a means of proof in thinning their numbers. Bring me a feather from any headdresses you acquire; for every set of five you bring me, you will earn recognition amongst the Timbermaw.');
(8467, 'Some of the Deadwood furbolgs wear a distinctive headdress that may be used as a means of proof in thinning their numbers. Bring me a feather from any headdresses you acquire; for every set of five you bring me, you will earn recognition amongst the Timbermaw.');
(8469, 'The Winterfall are known to carry spirit beads to ward against foul spirits. These beads have clearly failed in their purpose, as the Winterfall themselves are the agents of corruption. Bring to me these spirit beads from fallen Winterfall furbolgs; for every set of five you bring me, you will earn recognition amongst the Timbermaw.');
(8828, 'Speak with Greatfather Winter. He is located near the Smokywood Pastures vendor area in Orgrimmar.');
(8874, 'Talk to the Lunar Festival Harbinger in the entrance to the Undercity. You can also talk to Lunar Festival Harbingers in other capital cities.');
(8917, 'Acquire 15 Silithus Venom Samples and 20 gold and bring them along with a set of Shadowcraft Bracers to Mokvar in Orgrimmar.\r\n');
(9121, 'Archmage Angela Dosantos at Light\'s Hope Chapel in the Eastern Plaguelands wants 5 Arcane Crystals, 2 Nexus Crystals, 1 Righteous Orb and 60 gold pieces. You must also be Honored with the Argent Dawn.\r\n');
(9126, 'Rohan the Assassin at Light\'s Hope Chapel in the Eastern Plaguelands wants 30 Bone Fragments.\r\n');
(9128, 'Archmage Angela Dosantos at Light\'s Hope Chapel in the Eastern Plaguelands wants 30 Core of Elements.\r\n');
(9141, 'Dispatch Commander Metz at Light\'s Hope Chapel in the Eastern Plaguelands wants an Argent Dawn Valor Token.\r\n');
(9184, 'Deliver 10 Wicked Leather Headbands and the Craftsman\'s Writ - Wicked Leather Headband - to Packmaster Stonebruiser at Light\'s Hope Chapel in the Eastern Plaguelands.\r\n');
(9185, 'Deliver 25 Rugged Armor Kits and the Craftsman\'s Writ - Rugged Armor Kit - to Packmaster Stonebruiser at Light\'s Hope Chapel in the Eastern Plaguelands.\r\n');
(9201, 'Deliver 15 Greater Arcane Protection Potions and the Craftsman\'s Writ - Greater Arcane Protection Potion - to Packmaster Stonebruiser at Light\'s Hope Chapel in the Eastern Plaguelands.\r\n');
(9265, 'Collect three Dim Necrotic Stones from the Scourge outside Undercity and investigate the glowing runic circles nearby their encampment.');
