INSERT INTO `creature_stats` (`Name`, `LevelMin`, `LevelMax`, `DamageMin`, `DamageMax`, `HealthMin`, `HealthMax`, `ManaMin`, `ManaMAx`, `ArmorMin`, `ArmorMax`, `FireResist`, `FrostResist`, `NatureResist`, `ShadowResist`, `ArcaneResist`) VALUES
-- Page 4
('7:XT', 41, 41, 59, 78, 1585, 1585, 0, 0, 2102, 2102, 0, 0, 0, 0, 0),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
-- Page 5
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
(NAME, LEVELMIN, LEVELMAX, DAMAGEMIN, DAMAGEMAX, HEALTHMIN, HEALTHMAX, MANAMIN, MANAMAX, ARMORMIN, ARMORMAX, FIRE, FROST, NATURE, SHADOW, ARCANE),
...