CREATE TABLE `skill_line_ability` (
	`ID` SMALLINT UNSIGNED NOT NULL,
	`build` SMALLINT(4) UNSIGNED NOT NULL COMMENT 'Game client build for which to load this entry',
	`skillId` INT UNSIGNED NOT NULL DEFAULT '0',
	`spellId` INT UNSIGNED NOT NULL DEFAULT '0',
	`raceMask` INT UNSIGNED NOT NULL DEFAULT '0',
	`classMask` INT UNSIGNED NOT NULL DEFAULT '0',
	`reqSkillValue` INT UNSIGNED NOT NULL DEFAULT '0',
	`supersededBySpell` INT UNSIGNED NOT NULL DEFAULT '0',
	`learnOnGetSkill` INT UNSIGNED NOT NULL DEFAULT '0',
	`maxValue` INT UNSIGNED NOT NULL DEFAULT '0',
	`minValue` INT UNSIGNED NOT NULL DEFAULT '0',
	`reqTrainPoints` INT UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`, `build`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
